// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $footer from "./islands/footer.jsx";
import * as $form_and_results from "./islands/form-and-results.jsx";
import * as $main_form from "./islands/main-form.jsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/footer.jsx": $footer,
    "./islands/form-and-results.jsx": $form_and_results,
    "./islands/main-form.jsx": $main_form,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
