"use strict";
// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.
Object.defineProperty(exports, "__esModule", { value: true });
var $_404 = require("./routes/_404.tsx");
var $_app = require("./routes/_app.tsx");
var $index = require("./routes/index.tsx");
var $footer = require("./islands/footer.jsx");
var $form_and_results = require("./islands/form-and-results.jsx");
var $main_form = require("./islands/main-form.jsx");
var manifest = {
    routes: {
        "./routes/_404.tsx": $_404,
        "./routes/_app.tsx": $_app,
        "./routes/index.tsx": $index,
    },
    islands: {
        "./islands/footer.jsx": $footer,
        "./islands/form-and-results.jsx": $form_and_results,
        "./islands/main-form.jsx": $main_form,
    },
    baseUrl: import.meta.url,
};
exports.default = manifest;
