// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $filters from "./islands/filters.tsx";
import * as $footer from "./islands/footer.tsx";
import * as $form_and_results from "./islands/form-and-results.tsx";
import * as $main_form from "./islands/main-form.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/filters.tsx": $filters,
    "./islands/footer.tsx": $footer,
    "./islands/form-and-results.tsx": $form_and_results,
    "./islands/main-form.tsx": $main_form,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
